package com.patrolmanagr.patrolmanagr.config;

public enum IncidentType {
    RETARD,
    PASTILLE_MANQUANTE,
    OMISSION_PASTILLE,
    SEQUENCE_INCORRECTE,
    HORS_PLAQUETTE,
    DOUBLE_SCAN,
    TEMPS_TRAJET_TROP_LONG,
    RONDE_INCOMPLETE,
    TERMINAL_INACTIF,
    COLLECTE_ECHEC,
    IMMOBILISATION,
    HORS_HORAIRE,
    EQUIPEMENT_DEFECTUEUX,
    AUTRE
}